/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Entrar */
        post: operations["entrar_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sair
         * @description Revoga a sessão de refresh e apaga o cookie.
         */
        post: operations["sair_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quem Sou Eu */
        get: operations["quem_sou_eu_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renovar
         * @description Troca o refresh por um access novo. O refresh antigo é revogado.
         */
        post: operations["renovar_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrar */
        post: operations["registrar_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Exercicios
         * @description Exercícios de uma aula, ou do bloco inteiro.
         *
         *     É o que a prova do bloco consome: sem isso a tela teria que baixar as dez
         *     aulas inteiras para montar uma lista de exercícios.
         */
        get: operations["listar_exercicios_api_exercises_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{exercise_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Revelar Resposta
         * @description Entrega o gabarito — só quando o usuário pede, e só se estiver logado.
         */
        get: operations["revelar_resposta_api_exercises__exercise_id__answer_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{exercise_id}/attempt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tentar
         * @description Confere a resposta e grava a tentativa.
         *
         *     A correção acontece aqui porque a resposta certa não faz parte do contrato
         *     de leitura: mandá-la ao navegador para o JavaScript comparar seria publicar
         *     o gabarito. A comparação é a mesma de `app/domain/answers.py` — a regra
         *     mora num lugar só.
         */
        post: operations["tentar_api_exercises__exercise_id__attempt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Readiness.
         *
         *     Abre uma conexão de verdade e pergunta a versão ao Postgres. Se o banco
         *     não responder, devolve 503 — é isso que faz o healthcheck valer alguma coisa.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Aulas
         * @description Todas as aulas, em ordem, com o mínimo para montar a navegação.
         */
        get: operations["listar_aulas_api_lessons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter Aula
         * @description Uma aula inteira: gramática, frases, vocabulário, pronúncia e exercícios.
         */
        get: operations["obter_aula_api_lessons__number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{number}/studied": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Marcar Estudada
         * @description Idempotente: marcar duas vezes não cria duas linhas.
         */
        put: operations["marcar_estudada_api_lessons__number__studied_put"];
        post?: never;
        /** Desmarcar Estudada */
        delete: operations["desmarcar_estudada_api_lessons__number__studied_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description Liveness: o processo está de pé. Não toca em dependência nenhuma.
         */
        get: operations["live_api_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meu Progresso
         * @description Uma linha por aula, sempre as dez — aula sem atividade vem zerada.
         */
        get: operations["meu_progresso_api_me_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vocab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Vocabulario
         * @description Vocabulário de uma aula, ou de todas. Base do deck de revisão da S4.
         */
        get: operations["listar_vocabulario_api_vocab_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttemptIn */
        AttemptIn: {
            /**
             * Answer
             * @description O que o usuário digitou.
             */
            answer: string;
        };
        /** AttemptOut */
        AttemptOut: {
            /** Correct */
            correct: boolean;
            /** Explanation */
            explanation: string;
        };
        /**
         * ExerciseOut
         * @description Exercício como ele chega ao cliente.
         *
         *     A resposta certa **não** faz parte deste schema. Na S3 a correção passa a
         *     ser feita pelo servidor; até lá o cliente corrige, mas o contrato já nasce
         *     no formato certo para não ter que mudar depois.
         */
        ExerciseOut: {
            /** Explanation */
            explanation: string;
            /** Hint */
            hint: string | null;
            /** Id */
            id: number;
            /** Position */
            position: number;
            /** Prompt */
            prompt: string;
        };
        /** ExerciseWithLessonOut */
        ExerciseWithLessonOut: {
            /** Explanation */
            explanation: string;
            /** Hint */
            hint: string | null;
            /** Id */
            id: number;
            /** Lesson Number */
            lesson_number: number;
            /** Position */
            position: number;
            /** Prompt */
            prompt: string;
        };
        /** GrammarBlockOut */
        GrammarBlockOut: {
            /** Heading */
            heading: string;
            /** Rows */
            rows: components["schemas"]["GrammarRowOut"][];
            /** Table Head */
            table_head: string[] | null;
            /** Warning */
            warning: string | null;
            /** Why */
            why: string;
        };
        /** GrammarRowOut */
        GrammarRowOut: {
            /**
             * Cells
             * @description Células da linha, na ordem do table_head do bloco.
             */
            cells: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Db */
            db: string;
            /** Env */
            env: string;
            /** Status */
            status: string;
            /** Version */
            version?: string | null;
        };
        /** LessonDetailOut */
        LessonDetailOut: {
            /** Exercises */
            exercises: components["schemas"]["ExerciseOut"][];
            /** Focus Points */
            focus_points: string[];
            /** Goals */
            goals: string[];
            /** Grammar Blocks */
            grammar_blocks: components["schemas"]["GrammarBlockOut"][];
            /** Grammar Tag */
            grammar_tag: string;
            /** Lead */
            lead: string;
            /** Number */
            number: number;
            /** Phrases */
            phrases: components["schemas"]["PhraseOut"][];
            /** Pronunciation */
            pronunciation: components["schemas"]["PronunciationNoteOut"][];
            /** Story Note */
            story_note: string | null;
            /** Title */
            title: string;
            /** Title Pt */
            title_pt: string;
            /** Voa Url */
            voa_url: string;
            /** Vocab */
            vocab: components["schemas"]["VocabItemOut"][];
        };
        /** LessonProgressOut */
        LessonProgressOut: {
            /** Attempts */
            attempts: number;
            /** Correct */
            correct: number;
            /** Lesson Number */
            lesson_number: number;
            /** Studied */
            studied: boolean;
            /** Studied At */
            studied_at: string | null;
        };
        /**
         * LessonSummaryOut
         * @description O que a trilha de navegação precisa — sem carregar a aula inteira.
         */
        LessonSummaryOut: {
            /** Focus Points */
            focus_points: string[];
            /** Grammar Tag */
            grammar_tag: string;
            /** Number */
            number: number;
            /** Story Note */
            story_note: string | null;
            /** Title */
            title: string;
            /** Title Pt */
            title_pt: string;
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** PhraseOut */
        PhraseOut: {
            /** Note */
            note: string;
            /** Text En */
            text_en: string;
            /** Text Pt */
            text_pt: string;
        };
        /** ProgressOut */
        ProgressOut: {
            /** Attempts */
            attempts: number;
            /** Correct */
            correct: number;
            /** Lessons */
            lessons: components["schemas"]["LessonProgressOut"][];
            /** Studied Count */
            studied_count: number;
            /** Total Lessons */
            total_lessons: number;
        };
        /** PronunciationNoteOut */
        PronunciationNoteOut: {
            /** Explanation */
            explanation: string;
            /** Label */
            label: string;
        };
        /** RegistroIn */
        RegistroIn: {
            /** Display Name */
            display_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Password
             * @description No mínimo 8 caracteres.
             */
            password: string;
        };
        /**
         * RevealAnswerOut
         * @description Só sai quando o usuário pede explicitamente para ver a resposta.
         */
        RevealAnswerOut: {
            /** Answers */
            answers: string[];
            /** Explanation */
            explanation: string;
        };
        /**
         * TokenOut
         * @description O access token volta no corpo; o refresh vai em cookie httpOnly.
         */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Expires In
             * @description Validade do access token, em segundos.
             */
            expires_in: number;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UsuarioOut */
        UsuarioOut: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Id */
            id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VocabItemOut */
        VocabItemOut: {
            /** Example En */
            example_en: string;
            /** Id */
            id: number;
            /** Ipa */
            ipa: string;
            /** Term */
            term: string;
            /** Translation Pt */
            translation_pt: string;
        };
        /** VocabItemWithLessonOut */
        VocabItemWithLessonOut: {
            /** Example En */
            example_en: string;
            /** Id */
            id: number;
            /** Ipa */
            ipa: string;
            /** Lesson Number */
            lesson_number: number;
            /** Term */
            term: string;
            /** Translation Pt */
            translation_pt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    entrar_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sair_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    quem_sou_eu_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioOut"];
                };
            };
        };
    };
    renovar_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
        };
    };
    registrar_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistroIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_exercicios_api_exercises_get: {
        parameters: {
            query?: {
                /** @description Filtra por número da aula. */
                lesson?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseWithLessonOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revelar_resposta_api_exercises__exercise_id__answer_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevealAnswerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tentar_api_exercises__exercise_id__attempt_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttemptIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    listar_aulas_api_lessons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonSummaryOut"][];
                };
            };
        };
    };
    obter_aula_api_lessons__number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    marcar_estudada_api_lessons__number__studied_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desmarcar_estudada_api_lessons__number__studied_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_api_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    meu_progresso_api_me_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressOut"];
                };
            };
        };
    };
    listar_vocabulario_api_vocab_get: {
        parameters: {
            query?: {
                /** @description Filtra por número da aula. */
                lesson?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabItemWithLessonOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
