/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Exercicios
         * @description Exercícios de uma aula, ou do bloco inteiro.
         *
         *     É o que a prova do bloco consome: sem isso a tela teria que baixar as dez
         *     aulas inteiras para montar uma lista de exercícios.
         */
        get: operations["listar_exercicios_api_exercises_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{exercise_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Revelar Resposta
         * @description Entrega o gabarito — só quando o usuário pede.
         */
        get: operations["revelar_resposta_api_exercises__exercise_id__answer_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{exercise_id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Conferir Resposta
         * @description Confere uma resposta sem entregar a certa.
         *
         *     A correção mora aqui, e não no cliente, porque a resposta certa não faz
         *     parte do contrato de leitura — mandá-la ao navegador para o JavaScript
         *     comparar seria o mesmo que publicar o gabarito. Na S3 este endpoint passa
         *     a gravar a tentativa do usuário logado; a resposta que ele devolve não muda.
         */
        post: operations["conferir_resposta_api_exercises__exercise_id__check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Readiness.
         *
         *     Abre uma conexão de verdade e pergunta a versão ao Postgres. Se o banco
         *     não responder, devolve 503 — é isso que faz o healthcheck valer alguma coisa.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Aulas
         * @description Todas as aulas, em ordem, com o mínimo para montar a navegação.
         */
        get: operations["listar_aulas_api_lessons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter Aula
         * @description Uma aula inteira: gramática, frases, vocabulário, pronúncia e exercícios.
         */
        get: operations["obter_aula_api_lessons__number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description Liveness: o processo está de pé. Não toca em dependência nenhuma.
         */
        get: operations["live_api_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vocab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Vocabulario
         * @description Vocabulário de uma aula, ou de todas. Base do deck de revisão da S4.
         */
        get: operations["listar_vocabulario_api_vocab_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CheckAnswerIn */
        CheckAnswerIn: {
            /**
             * Answer
             * @description O que o usuário digitou.
             */
            answer: string;
        };
        /** CheckAnswerOut */
        CheckAnswerOut: {
            /** Correct */
            correct: boolean;
            /** Explanation */
            explanation: string;
        };
        /**
         * ExerciseOut
         * @description Exercício como ele chega ao cliente.
         *
         *     A resposta certa **não** faz parte deste schema. Na S3 a correção passa a
         *     ser feita pelo servidor; até lá o cliente corrige, mas o contrato já nasce
         *     no formato certo para não ter que mudar depois.
         */
        ExerciseOut: {
            /** Explanation */
            explanation: string;
            /** Hint */
            hint: string | null;
            /** Id */
            id: number;
            /** Position */
            position: number;
            /** Prompt */
            prompt: string;
        };
        /** ExerciseWithLessonOut */
        ExerciseWithLessonOut: {
            /** Explanation */
            explanation: string;
            /** Hint */
            hint: string | null;
            /** Id */
            id: number;
            /** Lesson Number */
            lesson_number: number;
            /** Position */
            position: number;
            /** Prompt */
            prompt: string;
        };
        /** GrammarBlockOut */
        GrammarBlockOut: {
            /** Heading */
            heading: string;
            /** Rows */
            rows: components["schemas"]["GrammarRowOut"][];
            /** Table Head */
            table_head: string[] | null;
            /** Warning */
            warning: string | null;
            /** Why */
            why: string;
        };
        /** GrammarRowOut */
        GrammarRowOut: {
            /**
             * Cells
             * @description Células da linha, na ordem do table_head do bloco.
             */
            cells: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Db */
            db: string;
            /** Env */
            env: string;
            /** Status */
            status: string;
            /** Version */
            version?: string | null;
        };
        /** LessonDetailOut */
        LessonDetailOut: {
            /** Exercises */
            exercises: components["schemas"]["ExerciseOut"][];
            /** Focus Points */
            focus_points: string[];
            /** Goals */
            goals: string[];
            /** Grammar Blocks */
            grammar_blocks: components["schemas"]["GrammarBlockOut"][];
            /** Grammar Tag */
            grammar_tag: string;
            /** Lead */
            lead: string;
            /** Number */
            number: number;
            /** Phrases */
            phrases: components["schemas"]["PhraseOut"][];
            /** Pronunciation */
            pronunciation: components["schemas"]["PronunciationNoteOut"][];
            /** Story Note */
            story_note: string | null;
            /** Title */
            title: string;
            /** Title Pt */
            title_pt: string;
            /** Voa Url */
            voa_url: string;
            /** Vocab */
            vocab: components["schemas"]["VocabItemOut"][];
        };
        /**
         * LessonSummaryOut
         * @description O que a trilha de navegação precisa — sem carregar a aula inteira.
         */
        LessonSummaryOut: {
            /** Focus Points */
            focus_points: string[];
            /** Grammar Tag */
            grammar_tag: string;
            /** Number */
            number: number;
            /** Story Note */
            story_note: string | null;
            /** Title */
            title: string;
            /** Title Pt */
            title_pt: string;
        };
        /** PhraseOut */
        PhraseOut: {
            /** Note */
            note: string;
            /** Text En */
            text_en: string;
            /** Text Pt */
            text_pt: string;
        };
        /** PronunciationNoteOut */
        PronunciationNoteOut: {
            /** Explanation */
            explanation: string;
            /** Label */
            label: string;
        };
        /**
         * RevealAnswerOut
         * @description Só sai quando o usuário pede explicitamente para ver a resposta.
         */
        RevealAnswerOut: {
            /** Answers */
            answers: string[];
            /** Explanation */
            explanation: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VocabItemOut */
        VocabItemOut: {
            /** Example En */
            example_en: string;
            /** Id */
            id: number;
            /** Ipa */
            ipa: string;
            /** Term */
            term: string;
            /** Translation Pt */
            translation_pt: string;
        };
        /** VocabItemWithLessonOut */
        VocabItemWithLessonOut: {
            /** Example En */
            example_en: string;
            /** Id */
            id: number;
            /** Ipa */
            ipa: string;
            /** Lesson Number */
            lesson_number: number;
            /** Term */
            term: string;
            /** Translation Pt */
            translation_pt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listar_exercicios_api_exercises_get: {
        parameters: {
            query?: {
                /** @description Filtra por número da aula. */
                lesson?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseWithLessonOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revelar_resposta_api_exercises__exercise_id__answer_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevealAnswerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conferir_resposta_api_exercises__exercise_id__check_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckAnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckAnswerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    listar_aulas_api_lessons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonSummaryOut"][];
                };
            };
        };
    };
    obter_aula_api_lessons__number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_api_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    listar_vocabulario_api_vocab_get: {
        parameters: {
            query?: {
                /** @description Filtra por número da aula. */
                lesson?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabItemWithLessonOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
