"""deck de revisao espacada

Revision ID: 436e2d910761
Revises: 994ec56019d4
Create Date: 2026-10-07 15:52:59.869811
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "436e2d910761"
down_revision: str | None = "994ec56019d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_card",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("vocab_item_id", sa.Integer(), nullable=False),
        sa.Column("ease_factor", sa.Float(), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("repetitions", sa.Integer(), nullable=False),
        sa.Column("lapses", sa.Integer(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vocab_item_id"], ["vocab_item.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "vocab_item_id", name="uq_card_user_item"),
    )
    op.create_index(op.f("ix_review_card_due_at"), "review_card", ["due_at"], unique=False)
    op.create_index(op.f("ix_review_card_user_id"), "review_card", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_review_card_vocab_item_id"), "review_card", ["vocab_item_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_card_vocab_item_id"), table_name="review_card")
    op.drop_index(op.f("ix_review_card_user_id"), table_name="review_card")
    op.drop_index(op.f("ix_review_card_due_at"), table_name="review_card")
    op.drop_table("review_card")
    # ### end Alembic commands ###
