"""conteudo das aulas

Revision ID: a3249904ec56
Revises:
Create Date: 2026-10-07 15:01:41.855660
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "a3249904ec56"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lesson",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("title_pt", sa.String(length=200), nullable=False),
        sa.Column("voa_url", sa.String(length=500), nullable=False),
        sa.Column("grammar_tag", sa.String(length=200), nullable=False),
        sa.Column("focus_points", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("story_note", sa.String(length=200), nullable=True),
        sa.Column("lead", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lesson_number"), "lesson", ["number"], unique=True)
    op.create_table(
        "exercise",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("hint", sa.String(length=200), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["lesson_id"], ["lesson.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lesson_id", "position", name="uq_exercise_lesson_position"),
    )
    op.create_index(op.f("ix_exercise_lesson_id"), "exercise", ["lesson_id"], unique=False)
    op.create_table(
        "grammar_block",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("heading", sa.String(length=300), nullable=False),
        sa.Column("why", sa.Text(), nullable=False),
        sa.Column("warning", sa.Text(), nullable=True),
        sa.Column("table_head", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["lesson_id"], ["lesson.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lesson_id", "position", name="uq_block_lesson_position"),
    )
    op.create_index(
        op.f("ix_grammar_block_lesson_id"), "grammar_block", ["lesson_id"], unique=False
    )
    op.create_table(
        "lesson_goal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["lesson_id"], ["lesson.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lesson_id", "position", name="uq_goal_lesson_position"),
    )
    op.create_index(op.f("ix_lesson_goal_lesson_id"), "lesson_goal", ["lesson_id"], unique=False)
    op.create_table(
        "phrase",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text_en", sa.Text(), nullable=False),
        sa.Column("text_pt", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["lesson_id"], ["lesson.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lesson_id", "position", name="uq_phrase_lesson_position"),
    )
    op.create_index(op.f("ix_phrase_lesson_id"), "phrase", ["lesson_id"], unique=False)
    op.create_table(
        "pronunciation_note",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["lesson_id"], ["lesson.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lesson_id", "position", name="uq_pron_lesson_position"),
    )
    op.create_index(
        op.f("ix_pronunciation_note_lesson_id"), "pronunciation_note", ["lesson_id"], unique=False
    )
    op.create_table(
        "vocab_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("term", sa.String(length=120), nullable=False),
        sa.Column("ipa", sa.String(length=160), nullable=False),
        sa.Column("translation_pt", sa.Text(), nullable=False),
        sa.Column("example_en", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["lesson_id"], ["lesson.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lesson_id", "term", name="uq_vocab_lesson_term"),
    )
    op.create_index(op.f("ix_vocab_item_lesson_id"), "vocab_item", ["lesson_id"], unique=False)
    op.create_table(
        "exercise_answer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercise.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exercise_id", "position", name="uq_answer_exercise_position"),
    )
    op.create_index(
        op.f("ix_exercise_answer_exercise_id"), "exercise_answer", ["exercise_id"], unique=False
    )
    op.create_table(
        "grammar_row",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("block_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("cells", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["block_id"], ["grammar_block.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("block_id", "position", name="uq_row_block_position"),
    )
    op.create_index(op.f("ix_grammar_row_block_id"), "grammar_row", ["block_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_grammar_row_block_id"), table_name="grammar_row")
    op.drop_table("grammar_row")
    op.drop_index(op.f("ix_exercise_answer_exercise_id"), table_name="exercise_answer")
    op.drop_table("exercise_answer")
    op.drop_index(op.f("ix_vocab_item_lesson_id"), table_name="vocab_item")
    op.drop_table("vocab_item")
    op.drop_index(op.f("ix_pronunciation_note_lesson_id"), table_name="pronunciation_note")
    op.drop_table("pronunciation_note")
    op.drop_index(op.f("ix_phrase_lesson_id"), table_name="phrase")
    op.drop_table("phrase")
    op.drop_index(op.f("ix_lesson_goal_lesson_id"), table_name="lesson_goal")
    op.drop_table("lesson_goal")
    op.drop_index(op.f("ix_grammar_block_lesson_id"), table_name="grammar_block")
    op.drop_table("grammar_block")
    op.drop_index(op.f("ix_exercise_lesson_id"), table_name="exercise")
    op.drop_table("exercise")
    op.drop_index(op.f("ix_lesson_number"), table_name="lesson")
    op.drop_table("lesson")
    # ### end Alembic commands ###
